In [54]:
# Importando librerías de interés
import pandas as pd
import numpy as np

In [55]:
#Nombre de columnas del archivo de 2012
cols_salud = [
'entidad',
'munici',
'locali',
'sexo',
'edad',
'aa402ms',
'aa403ms',
'aa404ms',
'localida',
'pondef'
]

In [56]:
#Nombre de columnas del archivo de 2016
cols_salud_16 = [
'entidad',
'munici',
'locali',
'sexo',
'edad',
'afv_s',
'afm_s',
'afw_s',
'rural',
'ponde_f'
]

In [57]:
# Actividad física de adultos y adolescentes en México en 2012
path = 'actividad_2012.csv'
df_salud_12 = pd.read_csv(path)
df_salud_12 = df_salud_12[cols_salud]
df_salud_12['anio'] = 2012
df_salud_12.head()

,entidad,munici,locali,sexo,edad,aa402ms,aa403ms,aa404ms,localida,pondef,anio
0,1,1,1,1,19,0,300,45,2,2284.825425,2012
1,1,1,1,1,35,0,160,150,2,2765.961838,2012
2,1,1,1,2,16,20,0,140,2,2760.672936,2012
3,1,1,1,2,18,100,100,100,2,1169.764558,2012
4,1,1,1,1,60,0,60,420,2,1174.993011,2012

In [58]:
# Actividad física de adultos y adolescentes en México en 2016
path = 'actividad_2016_15-19.csv'
df_salud_16_adol = pd.read_csv(path, dtype='unicode', encoding='latin1')
df_salud_16_adol = df_salud_16_adol[cols_salud_16]
df_salud_16_adol['anio'] = 2016
df_salud_16_adol['entidad'] = df_salud_16_adol['entidad'].astype(int)
df_salud_16_adol['entidad'] = df_salud_16_adol['entidad'].astype(str)
df_salud_16_adol['munici'] = df_salud_16_adol['munici'].astype(int)
df_salud_16_adol['munici'] = df_salud_16_adol['munici'].astype(str)
df_salud_16_adol['locali'] = df_salud_16_adol['locali'].astype(int)
df_salud_16_adol['locali'] = df_salud_16_adol['locali'].astype(str)

path = 'actividad_2016_mayores.csv'
df_salud_16_mayores = pd.read_csv(path, dtype='unicode', encoding='latin1')
df_salud_16_mayores = df_salud_16_mayores[cols_salud_16]
df_salud_16_mayores['anio'] = 2016
df_salud_16_mayores['entidad'] = df_salud_16_mayores['entidad'].astype(int)
df_salud_16_mayores['entidad'] = df_salud_16_mayores['entidad'].astype(str)
df_salud_16_mayores['munici'] = df_salud_16_mayores['munici'].astype(int)
df_salud_16_mayores['munici'] = df_salud_16_mayores['munici'].astype(str)
df_salud_16_mayores['locali'] = df_salud_16_mayores['locali'].astype(int)
df_salud_16_mayores['locali'] = df_salud_16_mayores['locali'].astype(str)


df_salud_16 = pd.concat([df_salud_16_adol, df_salud_16_mayores], axis=0)
df_salud_16.rename(columns={'afv_s': 'aa402ms',
                   'afm_s': 'aa403ms',
                   'afw_s': 'aa404ms',
                   'rural': 'localida',
                   'ponde_f': 'pondef',
                   },
          inplace=True)
df_salud = pd.concat([df_salud_12, df_salud_16], axis=0)
df_salud.rename(columns={'aa402ms': 'actividad_vigorosa',
                   'aa403ms': 'actividad_moderada',
                   'aa404ms': 'actividad_caminar',
                   'localida': 'urbanizacion',
                   'pondef': 'ponderador',
                   },
          inplace=True)
df_salud.tail()

,entidad,munici,locali,sexo,edad,actividad_vigorosa,actividad_moderada,actividad_caminar,urbanizacion,ponderador,anio
7498,32,24,14,2,33,0,0,0,1,1181.4696594914346,2016
7499,32,26,17,1,25,1260,420,280,1,6979.742307012237,2016
7500,32,17,1,2,25,0,70,84,2,6765.249546552946,2016
7501,32,24,14,2,24,420,105,0,1,1181.4696594914346,2016
7502,32,10,108,1,36,0,0,40,1,4028.889108115514,2016

In [59]:
#Creación del ID de localidad concatenando entidad, municipio y número de localidad
df_salud['localidad'] = df_salud['entidad'].astype(str) + '_' + df_salud['munici'].astype(str) + '_' + df_salud['locali'].astype(str)
df_salud.drop(['entidad', 'munici', 'locali'], axis=1, inplace=True)
df_salud.head()

,sexo,edad,actividad_vigorosa,actividad_moderada,actividad_caminar,urbanizacion,ponderador,anio,localidad
0,1,19,0,300,45,2,2284.825425,2012,1_1_1
1,1,35,0,160,150,2,2765.961838,2012,1_1_1
2,2,16,20,0,140,2,2760.672936,2012,1_1_1
3,2,18,100,100,100,2,1169.764558,2012,1_1_1
4,1,60,0,60,420,2,1174.993011,2012,1_1_1

In [60]:
#Filtro de valores nulos 
df_salud_filtrada = df_salud[['localidad', 'actividad_vigorosa', 'actividad_moderada', 'actividad_caminar', 'urbanizacion', 'ponderador', 'anio']]
df_salud_filtrada['actividad_vigorosa'] = df_salud_filtrada['actividad_vigorosa'].astype(str).replace(' ','0')
df_salud_filtrada['actividad_moderada'] = df_salud_filtrada['actividad_moderada'].astype(str).replace(' ','0')
df_salud_filtrada['actividad_caminar'] = df_salud_filtrada['actividad_caminar'].astype(str).replace(' ','0')
df_salud_filtrada['urbanizacion'] = df_salud_filtrada['urbanizacion'].astype(str).replace(' ','3')
df_salud_filtrada['ponderador'] = df_salud_filtrada['ponderador'].astype(str).replace(' ','0')
df_salud_filtrada.fillna(0, inplace=True)
df_salud_filtrada['actividad_vigorosa'] = df_salud_filtrada['actividad_vigorosa'].astype(str).replace('nan','0')
df_salud_filtrada['actividad_moderada'] = df_salud_filtrada['actividad_moderada'].astype(str).replace('nan','0')
df_salud_filtrada['actividad_caminar'] = df_salud_filtrada['actividad_caminar'].astype(str).replace('nan','0')
df_salud_filtrada['urbanizacion'] = df_salud_filtrada['urbanizacion'].astype(str).replace('nan','0')

#Pasamos los datos de muestra a población usando la variable de ponderador. Se tiene que multiplicar el ponderador con el valor correspondiente.
df_salud_filtrada['act_vig_tot'] = df_salud_filtrada['actividad_vigorosa'].astype(float) * df_salud_filtrada['ponderador'].astype(float)
df_salud_filtrada['act_mod_tot'] = df_salud_filtrada['actividad_moderada'].astype(float) * df_salud_filtrada['ponderador'].astype(float)
df_salud_filtrada['act_cam_tot'] = df_salud_filtrada['actividad_caminar'].astype(float) * df_salud_filtrada['ponderador'].astype(float)
df_salud_filtrada['ponderador'] = df_salud_filtrada['ponderador'].astype(float)
df_salud_filtrada['localidad'] = df_salud_filtrada['localidad'].astype(str)
df_salud_filtrada.tail(50)

/var/folders/49/2cjkmjwj4sv_3xdjt01gj1t40000gn/T/ipykernel_38245/4139852802.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salud_filtrada['actividad_vigorosa'] = df_salud_filtrada['actividad_vigorosa'].astype(str).replace(' ','0')
/var/folders/49/2cjkmjwj4sv_3xdjt01gj1t40000gn/T/ipykernel_38245/4139852802.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salud_filtrada['actividad_moderada'] = df_salud_filtrada['actividad_moderada'].astype(str).replace(' ','0')
/var/folders/49/2cjkmjwj4sv_3xdjt01gj1t40000gn/T/ipykernel_38245/4139852802.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salud_filtrada['actividad_caminar'] = df_salud_filtrada['actividad_caminar'].astype(str).replace(' ','0')
/var/folders/49/2cjkmjwj4sv_3xdjt01gj1t40000gn/T/ipykernel_38245/4139852802.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salud_filtrada['urbanizacion'] = df_salud_filtrada['urbanizacion'].astype(str).replace(' ','3')
/var/folders/49/2cjkmjwj4sv_3xdjt01gj1t40000gn/T/ipykernel_38245/4139852802.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salud_filtrada['ponderador'] = df_salud_filtrada['ponderador'].astype(str).replace(' ','0')
/var/folders/49/2cjkmjwj4sv_3xdjt01gj1t40000gn/T/ipykernel_38245/4139852802.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salud_filtrada.fillna(0, inplace=True)
/var/folders/49/2cjkmjwj4sv_3xdjt01gj1t40000gn/T/ipykernel_38245/4139852802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salud_filtrada['actividad_vigorosa'] = df_salud_filtrada['actividad_vigorosa'].astype(str).replace('nan','0')
/var/folders/49/2cjkmjwj4sv_3xdjt01gj1t40000gn/T/ipykernel_38245/4139852802.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salud_filtrada['actividad_moderada'] = df_salud_filtrada['actividad_moderada'].astype(str).replace('nan','0')
/var/folders/49/2cjkmjwj4sv_3xdjt01gj1t40000gn/T/ipykernel_38245/4139852802.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salud_filtrada['actividad_caminar'] = df_salud_filtrada['actividad_caminar'].astype(str).replace('nan','0')
/var/folders/49/2cjkmjwj4sv_3xdjt01gj1t40000gn/T/ipykernel_38245/4139852802.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salud_filtrada['urbanizacion'] = df_salud_filtrada['urbanizacion'].astype(str).replace('nan','0')
/var/folders/49/2cjkmjwj4sv_3xdjt01gj1t40000gn/T/ipykernel_38245/4139852802.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salud_filtrada['act_vig_tot'] = df_salud_filtrada['actividad_vigorosa'].astype(float) * df_salud_filtrada['ponderador'].astype(float)

,localidad,actividad_vigorosa,actividad_moderada,actividad_caminar,urbanizacion,ponderador,anio,act_vig_tot,act_mod_tot,act_cam_tot
7453,32_24_43,540,0,0,1,8029.455381,2016,4.335906e+06,0.000000e+00,0.000000e+00
7454,32_26_17,0,0,0,1,6549.652661,2016,0.000000e+00,0.000000e+00,0.000000e+00
7455,32_24_6,0,0,30,1,539.081907,2016,0.000000e+00,0.000000e+00,1.617246e+04
7456,32_45_32,0,0,120,1,1169.853539,2016,0.000000e+00,0.000000e+00,1.403824e+05
7457,32_10_66,0,0,0,1,818.634309,2016,0.000000e+00,0.000000e+00,0.000000e+00
7458,32_45_45,0,0,0,1,1963.729104,2016,0.000000e+00,0.000000e+00,0.000000e+00
7459,32_24_43,90,420,420,1,8029.455381,2016,7.226510e+05,3.372371e+06,3.372371e+06
7460,32_6_1,0,360,210,2,4963.844260,2016,0.000000e+00,1.786984e+06,1.042407e+06
7461,32_45_32,120,210,420,1,854.702564,2016,1.025643e+05,1.794875e+05,3.589751e+05
7462,32_17_1,240,1260,120,2,9788.020621,2016,2.349125e+06,1.233291e+07,1.174562e+06
7463,32_6_1,0,1260,210,2,9937.539338,2016,0.000000e+00,1.252130e+07,2.086883e+06
7464,32_24_14,0,0,210,1,5995.529474,2016,0.000000e+00,0.000000e+00,1.259061e+06
7465,32_39_31,0,0,105,1,19013.394630,2016,0.000000e+00,0.000000e+00,1.996406e+06
7466,32_26_17,300,180,105,1,6837.422753,2016,2.051227e+06,1.230736e+06,7.179294e+05
7467,32_24_43,0,80,210,1,1433.227360,2016,0.000000e+00,1.146582e+05,3.009777e+05
7468,32_26_17,0,0,120,1,20939.226921,2016,0.000000e+00,0.000000e+00,2.512707e+06
7469,32_24_6,60,210,420,1,3020.130820,2016,1.812078e+05,6.342275e+05,1.268455e+06
7470,32_24_43,0,0,90,1,2866.454721,2016,0.000000e+00,0.000000e+00,2.579809e+05
7471,32_17_1,0,0,0,2,6603.785015,2016,0.000000e+00,0.000000e+00,0.000000e+00
7472,32_45_32,0,1260,30,1,584.926769,2016,0.000000e+00,7.370077e+05,1.754780e+04
7473,32_26_17,300,840,150,1,5501.668404,2016,1.650501e+06,4.621401e+06,8.252503e+05
7474,32_17_1,0,0,0,2,12527.205496,2016,0.000000e+00,0.000000e+00,0.000000e+00
7475,32_17_1,180,1260,0,2,6906.178501,2016,1.243112e+06,8.701785e+06,0.000000e+00
7476,32_45_32,0,0,210,1,1169.853539,2016,0.000000e+00,0.000000e+00,2.456692e+05
7477,32_17_1,180,360,80,2,17465.709222,2016,3.143828e+06,6.287655e+06,1.397257e+06
7478,32_26_17,0,0,30,1,8252.502605,2016,0.000000e+00,0.000000e+00,2.475751e+05
7479,32_24_43,70,0,0,1,1433.227360,2016,1.003259e+05,0.000000e+00,0.000000e+00
7480,32_17_1,0,0,70,2,57190.851224,2016,0.000000e+00,0.000000e+00,4.003360e+06
7481,32_45_45,0,360,0,1,2370.144443,2016,0.000000e+00,8.532520e+05,0.000000e+00
7482,32_24_6,0,0,0,1,2156.327630,2016,0.000000e+00,0.000000e+00,0.000000e+00
7483,32_6_1,0,0,0,2,6814.312689,2016,0.000000e+00,0.000000e+00,0.000000e+00
7484,32_6_1,0,1260,180,2,11848.284645,2016,0.000000e+00,1.492884e+07,2.132691e+06
7485,32_39_31,0,0,0,1,11814.835748,2016,0.000000e+00,0.000000e+00,0.000000e+00
7486,32_17_1,0,50,60,2,7467.940074,2016,0.000000e+00,3.733970e+05,4.480764e+05
7487,32_17_1,0,0,210,2,5835.008571,2016,0.000000e+00,0.000000e+00,1.225352e+06
7488,32_17_1,0,180,70,2,7068.023349,2016,0.000000e+00,1.272244e+06,4.947616e+05
7489,32_6_1,0,50,45,2,10048.790257,2016,0.000000e+00,5.024395e+05,4.521956e+05
7490,32_10_66,0,0,60,1,1196.199044,2016,0.000000e+00,0.000000e+00,7.177194e+04
7491,32_6_1,0,240,0,2,9977.515768,2016,0.000000e+00,2.394604e+06,0.000000e+00
7492,32_10_108,1260,40,80,1,6043.333662,2016,7.614600e+06,2.417333e+05,4.834667e+05
7493,32_6_1,150,70,240,2,6196.753992,2016,9.295131e+05,4.337728e+05,1.487221e+06
7494,32_10_66,1080,840,420,1,1384.757277,2016,1.495538e+06,1.163196e+06,5.815981e+05
7495,32_10_66,0,0,40,1,649.714473,2016,0.000000e+00,0.000000e+00,2.598858e+04
7496,32_6_1,0,0,105,2,6246.453298,2016,0.000000e+00,0.000000e+00,6.558776e+05
7497,32_10_108,0,120,210,1,4028.889108,2016,0.000000e+00,4.834667e+05,8.460667e+05
7498,32_24_14,0,0,0,1,1181.469659,2016,0.000000e+00,0.000000e+00,0.000000e+00
7499,32_26_17,1260,420,280,1,6979.742307,2016,8.794475e+06,2.931492e+06,1.954328e+06
7500,32_17_1,0,70,84,2,6765.249547,2016,0.000000e+00,4.735675e+05,5.682810e+05
7501,32_24_14,420,105,0,1,1181.469659,2016,4.962173e+05,1.240543e+05,0.000000e+00
7502,32_10_108,0,0,40,1,4028.889108,2016,0.000000e+00,0.000000e+00,1.611556e+05

In [61]:
#Agrupación por localidad, año, y urbanización. También se saca el promedio de cada una dividiendo entre el ponderador
df_salud_filtrada = df_salud_filtrada.groupby(['localidad',  'anio', 'urbanizacion'], as_index=False).sum().sort_values(by='localidad', ascending=True)
df_salud_filtrada['actividad_vigorosa_promedio'] = df_salud_filtrada['act_vig_tot'].div(df_salud_filtrada['ponderador'])
df_salud_filtrada['actividad_moderada_promedio'] = df_salud_filtrada['act_mod_tot'].div(df_salud_filtrada['ponderador'])
df_salud_filtrada['actividad_caminar_promedio'] = df_salud_filtrada['act_cam_tot'].div(df_salud_filtrada['ponderador'])
df_salud_filtrada.head(10)

,localidad,anio,urbanizacion,ponderador,act_vig_tot,act_mod_tot,act_cam_tot,actividad_vigorosa_promedio,actividad_moderada_promedio,actividad_caminar_promedio
0,10_12_1,2012,2,83713.195427,1.233804e+06,3.690044e+07,6.639771e+06,14.738467,440.795993,79.315704
1,10_12_193,2012,1,6544.073875,2.846655e+06,3.150303e+06,1.761395e+06,434.997450,481.397839,269.158761
2,10_12_24,2012,1,30690.234850,2.143512e+06,7.119076e+06,3.480514e+06,69.843467,231.965519,113.407881
3,10_12_6,2012,1,12673.836618,0.000000e+00,1.467946e+07,1.369236e+06,0.000000,1158.248767,108.036407
4,10_13_335,2012,1,3915.971818,0.000000e+00,6.803165e+05,8.672379e+05,0.000000,173.728661,221.461741
5,10_13_445,2012,1,3581.609123,1.153065e+06,7.095688e+05,3.412648e+06,321.940532,198.114520,952.825259
6,10_14_213,2016,1,16735.853165,8.740821e+06,5.331957e+06,6.785888e+06,522.281189,318.594879,405.470119
7,10_14_28,2012,1,3483.894274,0.000000e+00,8.621185e+05,1.780592e+05,0.000000,247.458294,51.109254
8,10_14_398,2012,1,2757.538360,4.964321e+04,2.481634e+06,3.475024e+05,18.002726,899.945487,126.019080
9,10_14_798,2012,1,3610.511236,1.964340e+06,9.881404e+05,2.310171e+06,544.061372,273.684334,639.846068

In [62]:
#Quitamos columnas que no nos importan para la tabla final
df_salud_filtrada = df_salud_filtrada[['localidad', 'urbanizacion', 'anio', 'actividad_vigorosa_promedio', 'actividad_moderada_promedio', 'actividad_caminar_promedio']]
df_salud_filtrada

,localidad,urbanizacion,anio,actividad_vigorosa_promedio,actividad_moderada_promedio,actividad_caminar_promedio
0,10_12_1,2,2012,14.738467,440.795993,79.315704
1,10_12_193,1,2012,434.997450,481.397839,269.158761
2,10_12_24,1,2012,69.843467,231.965519,113.407881
3,10_12_6,1,2012,0.000000,1158.248767,108.036407
4,10_13_335,1,2012,0.000000,173.728661,221.461741
...,...,...,...,...,...,...
2121,9_7_1,2,2012,131.522855,313.824574,445.979493
2122,9_7_1,2,2016,207.504581,412.945890,334.397865
2123,9_8_1,2,2012,52.507406,266.005447,327.973540
2124,9_9_11,2,2012,171.009187,160.650870,44.462524
2125,9_9_24,2,2012,1260.000000,1260.000000,1260.000000

In [63]:
#Exportamos la tabla final
df_salud_filtrada.to_csv('df_salud_filtrada.csv')